[package]
name = "boardswarm-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
bytes = "1.3.0"
clap = { version = "4.0.32", features = ["derive"] }
crossterm = "0.25.0"
derive = "1.0.0"
features = "0.10.0"
futures = "0.3.25"
mprocs-vt100 = "0.1.1"
nix = "0.26.1"
boardswarm-protocol = { version = "0.1.0", path = "../boardswarm-protocol" }
tokio = { version = "1.23.0", features = ["full"] }
tokio-util = "0.7.4"
tonic = "0.8.3"
tui = "0.19.0"
